### Create new enrollment
POST http://localhost:3000/api/enrollment HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJmaXJzdG5hbWUiOiJBYmViZSIsImxhc3RuYW1lIjoiS2ViZWRlIiwiZW1haWwiOiJhYmViZS5rZWJlZGVAZ21haWwuY29tIn0sImlhdCI6MTY3NjA1MzA4NCwiZXhwIjoxNjc2MDYzMDg0fQ.xPjvJkPIooQc4QlYDBh_aUgJKpuX7gxzbSyRwbdIG7Q
Content-Type: application/json

{
    "courseId": 2,
    "deadline": "2024-04-04"
}


### Get user enrollments
GET http://localhost:3000/api/enrollment HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJmaXJzdG5hbWUiOiJBYmViZSIsImxhc3RuYW1lIjoiS2ViZWRlIiwiZW1haWwiOiJhYmViZS5rZWJlZGVAZ21haWwuY29tIn0sImlhdCI6MTY3NjA1MzA4NCwiZXhwIjoxNjc2MDYzMDg0fQ.xPjvJkPIooQc4QlYDBh_aUgJKpuX7gxzbSyRwbdIG7Q


### Update enrollment deadline
PUT http://localhost:3000/api/enrollment/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJmaXJzdG5hbWUiOiJBYmViZSIsImxhc3RuYW1lIjoiS2ViZWRlIiwiZW1haWwiOiJhYmViZS5rZWJlZGVAZ21haWwuY29tIn0sImlhdCI6MTY3NjA1MzA4NCwiZXhwIjoxNjc2MDYzMDg0fQ.xPjvJkPIooQc4QlYDBh_aUgJKpuX7gxzbSyRwbdIG7Q
Content-Type: application/json

{    
    "deadline": "2023-04-04"
}



### Delete enrollment
DELETE  http://localhost:3000/api/enrollment/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJmaXJzdG5hbWUiOiJBYmViZSIsImxhc3RuYW1lIjoiS2ViZWRlIiwiZW1haWwiOiJhYmViZS5rZWJlZGVAZ21haWwuY29tIn0sImlhdCI6MTY3NjA1MzA4NCwiZXhwIjoxNjc2MDYzMDg0fQ.xPjvJkPIooQc4QlYDBh_aUgJKpuX7gxzbSyRwbdIG7Q
Content-Type: application/json